name: neotelemetri_or11
description: Neo Telemtri Open Recruitment application.

version: 1.0.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  video_player: ^0.10.5
  intro_slider: ^2.2.8
  flutter_screenutil: ^0.7.0
  font_awesome_flutter: ^8.5.0
  http: ^0.12.0+4
  shared_preferences: ^0.5.6
  rflutter_alert: ^1.0.3
  gradient_widgets: ^0.5.1
  charts_flutter: ^0.8.1
  json_annotation: ^3.0.0
  flutter_custom_clippers: ^0.1.6
  html_unescape: ^1.0.1+2
  auto_size_text: ^2.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  json_serializable:

flutter:

  uses-material-design: true

  assets:
    - assets/images/logo_mmd.png
    - assets/images/logo_neo.png
    - assets/images/logo_or_11.png
    - assets/images/logo_programming.png
    - assets/images/logo_skj.png
    - assets/images/avatar.jpg
    - assets/images/image_01.png
    - assets/images/image_02.png
    - assets/images/wrong.png
    - assets/images/profile_header_background.jpg
    - assets/images/bad.png
    - assets/images/good.png
    - assets/images/success.png

  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
        - asset: assets/fonts/RobotoMono-Bold.ttf

    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf

    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Bold.ttf

    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700

    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/WorkSans-Medium.ttf

    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf

    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

    - family: Quando
      fonts:
        - asset: assets/fonts/Quando.ttf

    - family: Satisfy
      fonts:
        - asset: assets/fonts/Satisfy.ttf

    - family: Alike
      fonts:
        - asset: assets/fonts/Alike-Regular.ttf