name: neotelemetri_or11
description: Neo Telemtri Open Recruitment application.

version: 1.0.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  font_awesome_flutter: ^8.5.0
  http: ^0.12.0+4
  shared_preferences: ^0.5.6+1
  rflutter_alert: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  json_serializable:

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-BoldItalic.ttf
          weight: 700

        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans-ExtraBoldItalic.ttf
          weight: 800

        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-LightItalic.ttf
          weight: 300

        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Italic.ttf
          weight: 400

        - asset: assets/fonts/OpenSans-Semibold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-SemiboldItalic.ttf
          weight: 600